fibriDB/mainApp/urls.py
from django.conf.urls import url
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns

from mainApp import views

# TEMPLATE TAGGING

app_name = 'mainApp'


# URL PATTERNS
urlpatterns = [
    path('api/users/', views.UserList.as_view(), name='user-list'),
    path('api/users/<int:pk>/', views.UserDetail.as_view()),
    path('api/items/', views.ItemList.as_view(), name='item-list'),
    path('api/items/<int:pk>/', views.ItemDetail.as_view()),
    path('api/', views.api_root, name='api'),
    path('editprofile', views.edit_profile, name='editprofile'),
    url(r'^api/items/nearestitems$', views.NearestItems.as_view()),
    url('item', views.edit_item, name='item'),
    url('login', views.user_login, name='login'),
    path('myItems', views.myItems.as_view(), name='myItems'),
    url(r'^register/$', views.register, name='register'),
    url('', views.mainView.as_view(), name='main'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

fibriDB/mainApp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class UserProfileInfo(models.Model):
    # Create relationship (don't inherit from User!)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # Add any additional attributes you want
    postalCode = models.IntegerField()
    street = models.CharField(max_length=150)
    language = models.CharField(choices=(('de', 'German'),
                                         ('fr', 'French'),
                                         ('it', 'Italian'),
                                         ('en', 'English')),
                                default='de',
                                max_length=50)

    def __str__(self):
        # Built-in attribute of django.contrib.auth.models.User !
        return self.user.username


class communities(models.Model):
    name = models.CharField(max_length=100)
    canton = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class communityinfo(models.Model):
    postalCode = models.IntegerField()
    commune = models.ForeignKey(communities, on_delete=models.CASCADE, null=True, blank=True)


class type(models.Model):
    name = models.CharField(choices=(('defib', 'Defibrillator'),
                                     ('sos', 'SOS Telephone')),
                            default='defib',
                            max_length=100)

    def __str__(self):
        return self.name


class items(models.Model):
    user = models.ForeignKey(User, related_name="items", on_delete=models.CASCADE, null=True, blank=True)
    type = models.ForeignKey(type, default="defib", on_delete=models.CASCADE)
    community = models.ForeignKey(communities, on_delete=models.CASCADE)
    longitude = models.DecimalField(decimal_places=10, max_digits=12)
    latitude = models.DecimalField(decimal_places=10, max_digits=12)
    availability = models.CharField(max_length=300, null=True, blank=True)
    pc = models.IntegerField()
    location = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    canton = models.CharField(max_length=100)
    location_descr = models.CharField(max_length=300)
    notes = models.CharField(max_length=300)
    responsible = models.CharField(max_length=100)

    def __str__(self):
        field_values = []
        for field in self._meta.get_fields():
            field_values.append(str(getattr(self, field.name, '')))
        return ",".join(field_values)

class defibModels(models.Model):
    name = models.CharField(max_length=100)
    modelNr = models.IntegerField()
    automatic = models.BooleanField(default=False)
    guided = models.BooleanField(default=False)
    compression = models.BooleanField(default=False)


class attributesDefib(models.Model):
    item = models.ForeignKey(items, on_delete=models.CASCADE)
    model = models.ForeignKey(defibModels, default=1, on_delete=models.CASCADE)

fibriDB/mainApp/forms.py
from django import forms
from django.contrib.auth.models import User
from mainApp.models import UserProfileInfo
from mainApp.models import items



class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('__all__')
        exclude = ('user', )


class EditProfileForm(forms.ModelForm):
    class Meta():
        model = User
        fields = (
                'email',
                'first_name',
                'last_name',
                'password'
            )


class ItemForm(forms.ModelForm):
    class Meta():
        model = items
        fields = ('__all__')
        exclude = ['user']

fibriDB/mainApp/views.py
# Extra Imports for the Login and Logout Capabilities
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import Http404
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.template import RequestContext
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import View
from rest_framework import permissions
from rest_framework import status, generics
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.reverse import reverse
from rest_framework.views import APIView

from mainApp import forms
from mainApp.models import items, UserProfileInfo
from mainApp.permissions import IsCreatorOrReadOnly
from mainApp.serializers import ItemsSerializer, UserSerializer, NearestItemSerializer
import requests

import math
from decimal import *


# Create your views here.
def index(request):
    return render(request, 'mainApp/index.html', )


class mainView(View):
    output = {}

    def get(self, request, output=output):
        
        URL = "http://127.0.0.1:8000/api/items/nearestitems?type=1&number=100&lat=12.0023&lng=12.0303"
        
        r = requests.get(url=URL)
        data = r.json()
        
        items = []
        
        for i in data:
            item = [float(i['latitude']), float(i['longitude'])]
            items.append(item)
        print(items)
        print("ITEMS")
        
        return render(request, 'mainApp/index.html', {'items': items})
        

@api_view(['GET'])
def api_root(request, format=None):
    return Response({
        'users': reverse('mainApp:user-list'),
        'items': reverse('mainApp:item-list')
    })


# Handling multiple items
class ItemList(APIView):
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]

    def get(self, request, format=None):
        item = items.objects.all()  # Get all items
        serializer = ItemsSerializer(item, many=True)  # Serialize the items with the defined attributes
        return Response(serializer.data)  # Return the serialized data as JSON

    def post(self, request, format=None):
        serializer = ItemsSerializer(data=request.data)  # Serialize the received items with the defined attributes
        if serializer.is_valid():
            serializer.save(user=self.request.user)  # Save the received items to DB
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


# Handling a single item
class ItemDetail(APIView):
    permission_classes = [permissions.IsAuthenticatedOrReadOnly, IsCreatorOrReadOnly]

    def get_object(self, pk):
        try:
            return items.objects.get(pk=pk)  # Get the item corresponding to the received primary key
        except items.DoesNotExist:
            raise Http404

    def get(self, request, pk, format=None):
        item = self.get_object(pk)
        serializer = ItemsSerializer(item)  # Serialize the item with the defined attributes
        return Response(serializer.data)  # Return the serialized data as JSON

    def put(self, request, pk, format=None):
        item = self.get_object(pk)
        serializer = ItemsSerializer(item, data=request.data)  # Serialize the received item with the defined attributes
        if serializer.is_valid():
            serializer.save()  # Save the received item to DB
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk, format=None):
        item = self.get_object(pk)
        item.delete()  # Delete the item from the DB
        return Response(status=status.HTTP_204_NO_CONTENT)


class NearestItems(APIView):
    def get(self, request, format=None):
        type = int(self.request.GET.get('type'))
        number = int(self.request.GET.get('number'))
        lat = Decimal(self.request.GET.get('lat'))
        lng = Decimal(self.request.GET.get('lng'))

        item_dist = []

        for item in items.objects.filter(type=type):
            d_lat = lat - item.latitude
            d_lng = lng - item.longitude

            temp = (
                    math.sin(d_lat / 2) ** 2
                    + math.cos(item.latitude)
                    * math.cos(lat)
                    * math.sin(d_lng / 2) ** 2
            )

            distance_m = 6373000 * (2 * math.atan2(math.sqrt(temp), math.sqrt(1 - temp)))  # Distance in meters
            item_dist.append([item, distance_m])

        item_dist.sort(key=lambda x: x[1], reverse=False)

        item_list = [i[0] for i in item_dist[0:number]]
        id_dist = dict([(p[0].id, p[1]) for p in item_dist[0:number]])

        serializer = NearestItemSerializer(item_list, many=True, context={'id_dist': id_dist})

        return Response(serializer.data)


class UserList(generics.ListAPIView):
    queryset = User.objects.all()
    serializer_class = UserSerializer


class UserDetail(generics.RetrieveAPIView):
    queryset = User.objects.all()
    serializer_class = UserSerializer


@login_required
def user_logout(request):
    logout(request)
    return render(request, 'mainApp/index.html', {})


class userAccount(View):
    def get(self, request):
        user = forms.UserForm
        form = forms.UserProfileInfoForm
        return render(request, 'mainApp/useraccount.html', {'user_form': user, 'profile_form': form})


def register(request):
    registered = False
    if request.method == "POST":
        user_form = forms.UserForm(data=request.POST)
        profile_form = forms.UserProfileInfoForm(data=request.POST)

        if user_form.is_valid and profile_form.is_valid:

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = forms.UserForm()
        profile_form = forms.UserProfileInfoForm()

    return render(request, 'mainApp/registration.html',
                  {'user_form': user_form,
                   'profile_form': profile_form,
                   'registered': registered})


@csrf_exempt
def user_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return render(request, 'mainApp/index.html', {})
            else:
                return HttpResponse('Account not active')
        else:
            print('Someone tried to login, but failed miserably')
            print('Username: {} and password {}'.format(username, password))
            return HttpResponse('Invalid login details supplied')
    else:
        return render(request, 'fibriDB/login.html', {})


@login_required
def edit_profile(request):
    print("I am running")
    print(request.user.id)
    profile = UserProfileInfo.objects.get(pk=request.user.id)
    form = forms.UserProfileInfoForm(instance=profile)
    UserForm = forms.UserForm(instance=request.user)
    args = {}
    if request.method == 'POST':
        print("I AM RETURNING")
        form = forms.UserForm(request.POST, instance=request.user)
        profileForm = forms.UserProfileInfoForm(instance=UserProfileInfo.objects.get(pk=request.user.id))
        print(form.is_valid())
        print(profileForm.is_valid())
        print(profileForm.errors)
        if form.is_valid():
            print("I AM RETURNING")
            user = form.save()
            user.set_password(user.password)
            user.save()
            
            profile = profileForm.save(commit=False)
            profile.user = user

            profile.save()
                        
            profile = UserProfileInfo.objects.get(pk=request.user.id)
            form = forms.UserProfileInfoForm(instance=profile)
            UserForm = forms.UserForm(instance=request.user)
            args['profile_form'] = form
            args['UserForm'] = UserForm
            print("I AM RETURNING")
            return render(request, 'mainApp/editprofile.html', args)
        else:
            print(form.errors)
            print(profileForm.errors)
            print(profileForm.non_field_errors)
            print("ERROR")
            return render(request, 'mainApp/editprofile.html')
    else:
        # args.update(csrf(request))
        # args['form'] = form
        args['UserForm'] = UserForm
        args['profile_form'] = form
        return render(request, 'mainApp/editprofile.html', args)


@login_required
def edit_item(request):
    if request.method == 'POST':
        form = forms.ItemForm(request.POST)
        print(form)

        if form.is_valid():
            # item_form = form.save()
            form.save()
            return render(request, 'mainApp/edititem.html', {'item_form': forms.ItemForm()})
        else:
            print(form.errors)
    else:
        form = forms.ItemForm(instance=request.user)
        args = {}
        # args.update(csrf(request))
        args['form'] = form
        return render(request, 'mainApp/edititem.html', {'item_form': form})

class myItems(View):
    def get(self, request):
        myitems = items.objects.all()
        return render(request, 'mainApp/myitems.html', {'myItems': myitems})

fibriDB/templates/mainApp/edititem.html
<!DOCTYPE html>
<!-- items -->
{% extends 'fibriDB/base.html' %}
{% load static %}
{% block body_block %}
<h1>Add Defibrillator-Location</h1>
{% if user.is_authenticated %}
<h2>Welcome {{ user.username }}!</h2>
<form class="registration" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{ item_form.as_p }}
  <input type="submit" name="" value="Submit">
</form>
<div id="map"></div>

<script>
    var map;
    function initMap() {
      map = new google.maps.Map(document.getElementById('map'), {
        center: {lat: 47, lng: 10},
        zoom: 8
      });

      var marker;
      function placeMarker(lat, long) {
        if ( marker ) {
          marker.setPosition(location);
        } else {
          marker = new google.maps.Marker({
            position: location,
            map: map
          });
        }


      }
      google.maps.event.addListener(map, 'click', function(event) {
        placeMarker(lat=event.latLng.lat(), long=event.latLng.lng());
        var sublong = parseFloat(long).toFixed(10);
        var sublat = parseFloat(lat).toFixed(10);
        $("#id_longitude").val(sublong);
        $("#id_latitude").val(sublat);
      });

    }
  </script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCkWSWnpxsBOeCI1OxJYzNCUISihFGKCL8&callback=initMap"
  async defer> </script>

  <script>

</script>
{% else %}
<h2>Please register to add locations!</h2>
{% endif %}

{% endblock body_block %}

fibriDB/templates/mainApp/editprofile.html
<!DOCTYPE html>
{% extends 'fibriDB/base.html' %}
{% load static %}
  {% block body_block %}

      <h1>Edit profile</h1>
      <form class="registration" method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {{ UserForm.as_table }}
              {{ profile_form.as_table }}
              <input type="submit" name="" value="Submit">
      </form>

  {% endblock body_block %}

fibriDB/templates/mainApp/index.html
<!DOCTYPE html>
{% extends 'fibriDB/base.html' %}
{% load static %}
{% block body_block %}

{% if user.is_authenticated %}
<h2>Welcome {{ user.username }}!</h2>
{% else %}
<h2>Welcome to the site!</h2>
{% endif %}
<div id="map" style="width: 100%; height: 800px;"></div>
<script>
var x = document.getElementById("demo");

function getLocation() {
  if (navigator.geolocation) {
    var pos = navigator.geolocation.getCurrentPosition(function(position) {

        // Get the coordinates of the current position.
        var lat = position.coords.latitude;
        var lng = position.coords.longitude;
        initMap(lat=lat, long=lng);
        return lat;
    })
  } else { 
    x.innerHTML = "Geolocation is not supported by this browser.";
  }
}

function showPosition(position) {
  return([position.coords.latitude, position.coords.longitude])
}

getLocation();

</script>
<script>
var map;
var locations = {{items}};
function initMap(lat, long) {
  var myOptions = {
    zoom: 10,
    center: new google.maps.LatLng(lat, long),
    mapTypeId: 'roadmap',
      styles: [
          {
              "elementType": "geometry",
              "stylers": [
                  {
                      "color": "#f5f5f5"
                  }
              ]
          },
          {
              "elementType": "labels.icon",
              "stylers": [
                  {
                      "visibility": "off"
                  }
              ]
          },
          {
              "elementType": "labels.text.fill",
              "stylers": [
                  {
                      "color": "#616161"
                  }
              ]
          },
          {
              "elementType": "labels.text.stroke",
              "stylers": [
                  {
                      "color": "#f5f5f5"
                  }
              ]
          },
          {
              "featureType": "administrative.land_parcel",
              "elementType": "labels.text.fill",
              "stylers": [
                  {
                      "color": "#bdbdbd"
                  }
              ]
          },
          {
              "featureType": "poi",
              "elementType": "geometry",
              "stylers": [
                  {
                      "color": "#eeeeee"
                  }
              ]
          },
          {
              "featureType": "poi",
              "elementType": "labels.text.fill",
              "stylers": [
                  {
                      "color": "#757575"
                  }
              ]
          },
          {
              "featureType": "poi.park",
              "elementType": "geometry",
              "stylers": [
                  {
                      "color": "#e5e5e5"
                  }
              ]
          },
          {
              "featureType": "poi.park",
              "elementType": "labels.text.fill",
              "stylers": [
                  {
                      "color": "#9e9e9e"
                  }
              ]
          },
          {
              "featureType": "road",
              "elementType": "geometry",
              "stylers": [
                  {
                      "color": "#ffffff"
                  }
              ]
          },
          {
              "featureType": "road.arterial",
              "elementType": "labels.text.fill",
              "stylers": [
                  {
                      "color": "#757575"
                  }
              ]
          },
          {
              "featureType": "road.highway",
              "elementType": "geometry",
              "stylers": [
                  {
                      "color": "#dadada"
                  }
              ]
          },
          {
              "featureType": "road.highway",
              "elementType": "labels.text.fill",
              "stylers": [
                  {
                      "color": "#616161"
                  }
              ]
          },
          {
              "featureType": "road.local",
              "elementType": "labels.text.fill",
              "stylers": [
                  {
                      "color": "#9e9e9e"
                  }
              ]
          },
          {
              "featureType": "transit.line",
              "elementType": "geometry",
              "stylers": [
                  {
                      "color": "#e5e5e5"
                  }
              ]
          },
          {
              "featureType": "transit.station",
              "elementType": "geometry",
              "stylers": [
                  {
                      "color": "#eeeeee"
                  }
              ]
          },
          {
              "featureType": "water",
              "elementType": "geometry",
              "stylers": [
                  {
                      "color": "#c9c9c9"
                  }
              ]
          },
          {
              "featureType": "water",
              "elementType": "labels.text.fill",
              "stylers": [
                  {
                      "color": "#9e9e9e"
                  }
              ]
          }
      ]
  }
  map = new google.maps.Map(document.getElementById('map'), myOptions);
  
  var infowindow = new google.maps.InfoWindow();
  var marker, i;
  for (i = 0; i < locations.length; i++) {
    marker = new google.maps.Marker({
      position: new google.maps.LatLng(locations[i][0], locations[i][1]),
      map: map
    });
  }
  
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCkWSWnpxsBOeCI1OxJYzNCUISihFGKCL8"
async defer> </script>

{% endblock body_block %}

fibriDB/templates/mainApp/myitems.html
<!DOCTYPE html>
{% extends 'fibriDB/base.html' %}
{% load static %}
  {% block body_block %}

      <h1>My Items</h1>
      {% for item in myItems %}
      <p>{{ item }}</p>
      {% endfor %}

  {% endblock body_block %}

fibriDB/templates/mainApp/registration.html
<!DOCTYPE html>
{% extends 'fibriDB/base.html' %}
{% load static %}
{% block body_block %}

  <h1>Registration</h1>

  {% if registered %}
  <h2>THANK YOU FOR YOUR REGISRATION</h2>
  {% else %}
  <form class="registration" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{ user_form.as_p }}
  {{ profile_form.as_p }}
  <input type="submit" name="" value="Submit">
  </form>
  {% endif %}

{% endblock %}