fibriDB/mainApp/urls.py
from django.conf.urls import url
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns

from mainApp import views

# TEMPLATE TAGGING

app_name = 'mainApp'


# URL PATTERNS
urlpatterns = [
    path('api/users/', views.UserList.as_view(), name='user-list'),
    path('api/users/<int:pk>/', views.UserDetail.as_view()),
    path('api/items/', views.ItemList.as_view(), name='item-list'),
    path('api/items/<int:pk>/', views.ItemDetail.as_view()),
    path('api/', views.api_root, name='api'),
    path('editprofile', views.edit_profile, name='editprofile'),
    url(r'^api/items/nearestitems$', views.NearestItems.as_view()),
    url('item', views.edit_item, name='item'),
    url('login', views.user_login, name='login'),
    path('myItems', views.myItems.as_view(), name='myItems'),
    url(r'^register/$', views.register, name='register'),
    url('', views.mainView.as_view(), name='main'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

fibriDB/templates/fibriDB/base.html
{% load static %}
<!DOCTYPE html>

<html>

<head>
  <meta charset="utf-8">
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
  <script src="{% static 'site.js' %}"></script>
  <title></title>
</head>

<body>

  <div class="main-container">
    <div class="inner-container">
      <div class="header">
        <img src="{% static 'logo-01.svg' %}">
    <div class="menu">
      {# Django Home Link / Admin Link / Register Link #}
      <li><a href="{% url 'mainApp:main' %}">Home</a></li>
      <li><a href="{% url 'mainApp:api' %}">API</a></li>

      {# Some logic on what to display for last item#}
      {% if user.is_authenticated %}
      <li><a href="{% url 'mainApp:item' %}">Add Item</a></li>
      <li><a href="{% url 'mainApp:myItems' %}">My Items</a></li>
      <li><a href="{% url 'logout' %}">Logout</a></li>
      <li><a href="{% url 'mainApp:editprofile' %}">Edit Profile</a></li>
      {% else %}
        <li><a href="{% url 'mainApp:login' %}">Login</a></li>
        <li><a href="{% url 'mainApp:register' %}">Register</a></li>
      {% endif %}
    </div>
    </div>
    <div class="content">

      {% block body_block %}
      <!-- Anything outside of this will be inherited of you extend! -->
      {% endblock %}
      </div>
    </div>
  </div>

</body>

</html>

fibriDB/templates/fibriDB/login.html
<!DOCTYPE html>
{% extends 'fibriDB/base.html' %}
{% load static %}
  {% block body_block %}

      <h1>Please login!</h1>
      <form class="login" method="post" action="{% url 'mainApp:login' %}">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Username">
        <input type="password" name="password" placeholder="Password">
        <input type="submit" name="" value="Login">

      </form>

  {% endblock body_block %}